version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.jetbrains.kotlin.jvm
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.jetbrains.kotlin.kapt
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.jetbrains.kotlin:kotlin-bom
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: io.github.oshai:kotlin-logging
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: com.github.ajalt.clikt:clikt
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: io.strikt:strikt-core
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.mockito.kotlin:mockito-kotlin
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily